//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanadaCitizenship.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CanadaCitizenship.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Date:.
        /// </summary>
        internal static string BeginDateLabel {
            get {
                return ResourceManager.GetString("BeginDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute.
        /// </summary>
        internal static string ComputeButton {
            get {
                return ResourceManager.GetString("ComputeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Profile.
        /// </summary>
        internal static string CurrentProfileLabel {
            get {
                return ResourceManager.GetString("CurrentProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Profile.
        /// </summary>
        internal static string DeleteProfileButton {
            get {
                return ResourceManager.GetString("DeleteProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Entry.
        /// </summary>
        internal static string FirstEntryLabel {
            get {
                return ResourceManager.GetString("FirstEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile.
        /// </summary>
        internal static string NewProfileButton {
            get {
                return ResourceManager.GetString("NewProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        internal static string OutOfCountry_Grid_Header_Begin {
            get {
                return ResourceManager.GetString("OutOfCountry.Grid.Header.Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string OutOfCountry_Grid_Header_Delete {
            get {
                return ResourceManager.GetString("OutOfCountry.Grid.Header.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string OutOfCountry_Grid_Header_End {
            get {
                return ResourceManager.GetString("OutOfCountry.Grid.Header.End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string OutOfCountryAddButton {
            get {
                return ResourceManager.GetString("OutOfCountryAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        internal static string OutOfCountryBeginLabel {
            get {
                return ResourceManager.GetString("OutOfCountryBeginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string OutOfCountryEndLabel {
            get {
                return ResourceManager.GetString("OutOfCountryEndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Residency.
        /// </summary>
        internal static string PermanentResidencyLabel {
            get {
                return ResourceManager.GetString("PermanentResidencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Date:.
        /// </summary>
        internal static string ProjectedDateLabel {
            get {
                return ResourceManager.GetString("ProjectedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Day(s):.
        /// </summary>
        internal static string RemainingDaysLabel {
            get {
                return ResourceManager.GetString("RemainingDaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total PR:.
        /// </summary>
        internal static string TotalPRLabel {
            get {
                return ResourceManager.GetString("TotalPRLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Temporary:.
        /// </summary>
        internal static string TotalTemporaryLabel {
            get {
                return ResourceManager.GetString("TotalTemporaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizenship Calculator.
        /// </summary>
        internal static string WindowName {
            get {
                return ResourceManager.GetString("WindowName", resourceCulture);
            }
        }
    }
}
